# -*- coding: utf-8 -*-
#
# This file is part of Flask-Breadcrumbs
# Copyright (C) 2013, 2014, 2016 CERN.
#
# Flask-Breadcrumbs is free software; you can redistribute it and/or
# modify it under the terms of the Revised BSD License; see LICENSE
# file for more details.

notifications:
  email: false

language: python

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: Xt9EigqRTy4q7pw1iP58a9k+YTC8WSaeSUJhsfCLvjKYvi5/eAQ/CJneQGliQm4yRIv69WwPsh7IuktmmcQpIdhkDZHN8BTa09B+C5aqx7LhulQGNQoX4oZ7sK0YPg/IRT0bFGLMbP6Hkri5Hr7e7zVFJg2Rkx9zWEtSC5qWTvM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.6'
    condition: "$REQUIREMENTS = release"
