# -*- coding: utf-8 -*-
# Copyright (C) 2022 Graz University of Technology.
#
# Copyright (C) 2022 Graz University of Technology.
# Flask-Breadcrumbs documentation build configuration file, created by
# Copyright (C) 2022 Graz University of Technology.
# sphinx-quickstart on Fri Jul 31 13:10:12 2015.
# Copyright (C) 2022 Graz University of Technology.
#
# Copyright (C) 2022 Graz University of Technology.
# This file is execfile()d with the current directory set to its
# Copyright (C) 2022 Graz University of Technology.
# containing dir.
# Copyright (C) 2022 Graz University of Technology.
#
# Copyright (C) 2022 Graz University of Technology.
# Note that not all possible configuration values are present in this
# Copyright (C) 2022 Graz University of Technology.
# autogenerated file.
# Copyright (C) 2022 Graz University of Technology.
#
# Copyright (C) 2022 Graz University of Technology.
# All configuration values have a default; values that are commented out
# Copyright (C) 2022 Graz University of Technology.
# serve to show the default.
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
import re
# Copyright (C) 2022 Graz University of Technology.
import shlex
# Copyright (C) 2022 Graz University of Technology.
import sys
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
from flask_breadcrumbs import __version__
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If extensions (or modules to document with autodoc) are in another directory,
# Copyright (C) 2022 Graz University of Technology.
# add these directories to sys.path here. If the directory is relative to the
# Copyright (C) 2022 Graz University of Technology.
# documentation root, use os.path.abspath to make it absolute, like shown here.
# Copyright (C) 2022 Graz University of Technology.
# sys.path.insert(0, os.path.abspath('.'))
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# -- General configuration ------------------------------------------------
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If your documentation needs a minimal Sphinx version, state it here.
# Copyright (C) 2022 Graz University of Technology.
# needs_sphinx = '1.0'
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Add any Sphinx extension module names here, as strings. They can be
# Copyright (C) 2022 Graz University of Technology.
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# Copyright (C) 2022 Graz University of Technology.
# ones.
# Copyright (C) 2022 Graz University of Technology.
extensions = [
# Copyright (C) 2022 Graz University of Technology.
    "sphinx.ext.autodoc",
# Copyright (C) 2022 Graz University of Technology.
    "sphinx.ext.coverage",
# Copyright (C) 2022 Graz University of Technology.
    "sphinx.ext.doctest",
# Copyright (C) 2022 Graz University of Technology.
    "sphinx.ext.intersphinx",
# Copyright (C) 2022 Graz University of Technology.
    "sphinx.ext.viewcode",
# Copyright (C) 2022 Graz University of Technology.
]
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Add any paths that contain templates here, relative to this directory.
# Copyright (C) 2022 Graz University of Technology.
# templates_path = ['_templates']
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The suffix(es) of source filenames.
# Copyright (C) 2022 Graz University of Technology.
# You can specify multiple suffix as a list of string:
# Copyright (C) 2022 Graz University of Technology.
# source_suffix = ['.rst', '.md']
# Copyright (C) 2022 Graz University of Technology.
source_suffix = ".rst"
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The encoding of source files.
# Copyright (C) 2022 Graz University of Technology.
# source_encoding = 'utf-8-sig'
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The master toctree document.
# Copyright (C) 2022 Graz University of Technology.
master_doc = "index"
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# General information about the project.
# Copyright (C) 2022 Graz University of Technology.
project = "Flask-Breadcrumbs"
# Copyright (C) 2022 Graz University of Technology.
copyright = "2014, 2015, 2016, CERN"
# Copyright (C) 2022 Graz University of Technology.
author = "Invenio Software"
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The version info for the project you're documenting, acts as replacement for
# Copyright (C) 2022 Graz University of Technology.
# |version| and |release|, also used in various other places throughout the
# Copyright (C) 2022 Graz University of Technology.
# built documents.
# Copyright (C) 2022 Graz University of Technology.
#
# Copyright (C) 2022 Graz University of Technology.
# The short X.Y version.
# Copyright (C) 2022 Graz University of Technology.
# The full version, including alpha/beta/rc tags.
# Copyright (C) 2022 Graz University of Technology.
release = __version__
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The language for content autogenerated by Sphinx. Refer to documentation
# Copyright (C) 2022 Graz University of Technology.
# for a list of supported languages.
# Copyright (C) 2022 Graz University of Technology.
#
# Copyright (C) 2022 Graz University of Technology.
# This is also used if you do content translation via gettext catalogs.
# Copyright (C) 2022 Graz University of Technology.
# Usually you set "language" from the command line for these cases.
# Copyright (C) 2022 Graz University of Technology.
language = "en"
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# There are two options for replacing |today|: either, you set today to some
# Copyright (C) 2022 Graz University of Technology.
# non-false value, then it is used:
# Copyright (C) 2022 Graz University of Technology.
# today = ''
# Copyright (C) 2022 Graz University of Technology.
# Else, today_fmt is used as the format for a strftime call.
# Copyright (C) 2022 Graz University of Technology.
# today_fmt = '%B %d, %Y'
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# List of patterns, relative to source directory, that match files and
# Copyright (C) 2022 Graz University of Technology.
# directories to ignore when looking for source files.
# Copyright (C) 2022 Graz University of Technology.
exclude_patterns = ["_build"]
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The reST default role (used for this markup: `text`) to use for all
# Copyright (C) 2022 Graz University of Technology.
# documents.
# Copyright (C) 2022 Graz University of Technology.
# default_role = None
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, '()' will be appended to :func: etc. cross-reference text.
# Copyright (C) 2022 Graz University of Technology.
# add_function_parentheses = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, the current module name will be prepended to all description
# Copyright (C) 2022 Graz University of Technology.
# unit titles (such as .. function::).
# Copyright (C) 2022 Graz University of Technology.
# add_module_names = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, sectionauthor and moduleauthor directives will be shown in the
# Copyright (C) 2022 Graz University of Technology.
# output. They are ignored by default.
# Copyright (C) 2022 Graz University of Technology.
# show_authors = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The name of the Pygments (syntax highlighting) style to use.
# Copyright (C) 2022 Graz University of Technology.
pygments_style = "sphinx"
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# A list of ignored prefixes for module index sorting.
# Copyright (C) 2022 Graz University of Technology.
# modindex_common_prefix = []
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, keep warnings as "system message" paragraphs in the built documents.
# Copyright (C) 2022 Graz University of Technology.
# keep_warnings = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, `todo` and `todoList` produce output, else they produce nothing.
# Copyright (C) 2022 Graz University of Technology.
todo_include_todos = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# -- Options for HTML output ----------------------------------------------
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The theme to use for HTML and HTML Help pages.  See the documentation for
# Copyright (C) 2022 Graz University of Technology.
# a list of builtin themes.
# Copyright (C) 2022 Graz University of Technology.
html_theme = "alabaster"
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Theme options are theme-specific and customize the look and feel of a theme
# Copyright (C) 2022 Graz University of Technology.
# further.  For a list of options available for each theme, see the
# Copyright (C) 2022 Graz University of Technology.
# documentation.
# Copyright (C) 2022 Graz University of Technology.
html_theme_options = {
# Copyright (C) 2022 Graz University of Technology.
    "description": "Flask-Breadcrumbs adds support for generating site breadcrumb navigation.",
# Copyright (C) 2022 Graz University of Technology.
    "github_user": "inveniosoftware",
# Copyright (C) 2022 Graz University of Technology.
    "github_repo": "flask-breadcrumbs",
# Copyright (C) 2022 Graz University of Technology.
    "github_button": False,
# Copyright (C) 2022 Graz University of Technology.
    "github_banner": True,
# Copyright (C) 2022 Graz University of Technology.
    "show_powered_by": False,
# Copyright (C) 2022 Graz University of Technology.
    "extra_nav_links": {
# Copyright (C) 2022 Graz University of Technology.
        "Flask-CLI@GitHub": "http://github.com/inveniosoftware/flask-breadcrumbs/",
# Copyright (C) 2022 Graz University of Technology.
        "Flask-CLI@PyPI": "http://pypi.python.org/pypi/Flask-Breadcrumbs/",
# Copyright (C) 2022 Graz University of Technology.
    },
# Copyright (C) 2022 Graz University of Technology.
}
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Add any paths that contain custom themes here, relative to this directory.
# Copyright (C) 2022 Graz University of Technology.
# html_theme_path = []
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The name for this set of Sphinx documents.  If None, it defaults to
# Copyright (C) 2022 Graz University of Technology.
# "<project> v<release> documentation".
# Copyright (C) 2022 Graz University of Technology.
# html_title = None
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# A shorter title for the navigation bar.  Default is the same as html_title.
# Copyright (C) 2022 Graz University of Technology.
# html_short_title = None
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The name of an image file (relative to this directory) to place at the top
# Copyright (C) 2022 Graz University of Technology.
# of the sidebar.
# Copyright (C) 2022 Graz University of Technology.
# html_logo = None
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The name of an image file (within the static path) to use as favicon of the
# Copyright (C) 2022 Graz University of Technology.
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# Copyright (C) 2022 Graz University of Technology.
# pixels large.
# Copyright (C) 2022 Graz University of Technology.
# html_favicon = None
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Add any paths that contain custom static files (such as style sheets) here,
# Copyright (C) 2022 Graz University of Technology.
# relative to this directory. They are copied after the builtin static files,
# Copyright (C) 2022 Graz University of Technology.
# so a file named "default.css" will overwrite the builtin "default.css".
# Copyright (C) 2022 Graz University of Technology.
# html_static_path = ['_static']
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Add any extra paths that contain custom files (such as robots.txt or
# Copyright (C) 2022 Graz University of Technology.
# .htaccess) here, relative to this directory. These files are copied
# Copyright (C) 2022 Graz University of Technology.
# directly to the root of the documentation.
# Copyright (C) 2022 Graz University of Technology.
# html_extra_path = []
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# Copyright (C) 2022 Graz University of Technology.
# using the given strftime format.
# Copyright (C) 2022 Graz University of Technology.
# html_last_updated_fmt = '%b %d, %Y'
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, SmartyPants will be used to convert quotes and dashes to
# Copyright (C) 2022 Graz University of Technology.
# typographically correct entities.
# Copyright (C) 2022 Graz University of Technology.
# html_use_smartypants = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Custom sidebar templates, maps document names to template names.
# Copyright (C) 2022 Graz University of Technology.
# html_sidebars = {}
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Additional templates that should be rendered to pages, maps page names to
# Copyright (C) 2022 Graz University of Technology.
# template names.
# Copyright (C) 2022 Graz University of Technology.
# html_additional_pages = {}
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If false, no module index is generated.
# Copyright (C) 2022 Graz University of Technology.
# html_domain_indices = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If false, no index is generated.
# Copyright (C) 2022 Graz University of Technology.
# html_use_index = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, the index is split into individual pages for each letter.
# Copyright (C) 2022 Graz University of Technology.
# html_split_index = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, links to the reST sources are added to the pages.
# Copyright (C) 2022 Graz University of Technology.
# html_show_sourcelink = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# Copyright (C) 2022 Graz University of Technology.
# html_show_sphinx = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# Copyright (C) 2022 Graz University of Technology.
# html_show_copyright = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, an OpenSearch description file will be output, and all pages will
# Copyright (C) 2022 Graz University of Technology.
# contain a <link> tag referring to it.  The value of this option must be the
# Copyright (C) 2022 Graz University of Technology.
# base URL from which the finished HTML is served.
# Copyright (C) 2022 Graz University of Technology.
# html_use_opensearch = ''
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# This is the file name suffix for HTML files (e.g. ".xhtml").
# Copyright (C) 2022 Graz University of Technology.
# html_file_suffix = None
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Language to be used for generating the HTML full-text search index.
# Copyright (C) 2022 Graz University of Technology.
# Sphinx supports the following languages:
# Copyright (C) 2022 Graz University of Technology.
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
# Copyright (C) 2022 Graz University of Technology.
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
# Copyright (C) 2022 Graz University of Technology.
# html_search_language = 'en'
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# A dictionary with options for the search language support, empty by default.
# Copyright (C) 2022 Graz University of Technology.
# Now only 'ja' uses this config value
# Copyright (C) 2022 Graz University of Technology.
# html_search_options = {'type': 'default'}
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The name of a javascript file (relative to the configuration directory) that
# Copyright (C) 2022 Graz University of Technology.
# implements a search results scorer. If empty, the default will be used.
# Copyright (C) 2022 Graz University of Technology.
# html_search_scorer = 'scorer.js'
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Output file base name for HTML help builder.
# Copyright (C) 2022 Graz University of Technology.
htmlhelp_basename = "Flask-Breadcrumbsdoc"
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# -- Options for LaTeX output ---------------------------------------------
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
latex_elements = {
# Copyright (C) 2022 Graz University of Technology.
    # The paper size ('letterpaper' or 'a4paper').
# Copyright (C) 2022 Graz University of Technology.
    #'papersize': 'letterpaper',
# Copyright (C) 2022 Graz University of Technology.
    # The font size ('10pt', '11pt' or '12pt').
# Copyright (C) 2022 Graz University of Technology.
    #'pointsize': '10pt',
# Copyright (C) 2022 Graz University of Technology.
    # Additional stuff for the LaTeX preamble.
# Copyright (C) 2022 Graz University of Technology.
    #'preamble': '',
# Copyright (C) 2022 Graz University of Technology.
    # Latex figure (float) alignment
# Copyright (C) 2022 Graz University of Technology.
    #'figure_align': 'htbp',
# Copyright (C) 2022 Graz University of Technology.
}
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Grouping the document tree into LaTeX files. List of tuples
# Copyright (C) 2022 Graz University of Technology.
# (source start file, target name, title,
# Copyright (C) 2022 Graz University of Technology.
#  author, documentclass [howto, manual, or own class]).
# Copyright (C) 2022 Graz University of Technology.
latex_documents = [
# Copyright (C) 2022 Graz University of Technology.
    (
# Copyright (C) 2022 Graz University of Technology.
        master_doc,
# Copyright (C) 2022 Graz University of Technology.
        "Flask-Breadcrumbs.tex",
# Copyright (C) 2022 Graz University of Technology.
        "Flask-Breadcrumbs Documentation",
# Copyright (C) 2022 Graz University of Technology.
        "Invenio Software",
# Copyright (C) 2022 Graz University of Technology.
        "manual",
# Copyright (C) 2022 Graz University of Technology.
    ),
# Copyright (C) 2022 Graz University of Technology.
]
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# The name of an image file (relative to this directory) to place at the top of
# Copyright (C) 2022 Graz University of Technology.
# the title page.
# Copyright (C) 2022 Graz University of Technology.
# latex_logo = None
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# For "manual" documents, if this is true, then toplevel headings are parts,
# Copyright (C) 2022 Graz University of Technology.
# not chapters.
# Copyright (C) 2022 Graz University of Technology.
# latex_use_parts = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, show page references after internal links.
# Copyright (C) 2022 Graz University of Technology.
# latex_show_pagerefs = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, show URL addresses after external links.
# Copyright (C) 2022 Graz University of Technology.
# latex_show_urls = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Documents to append as an appendix to all manuals.
# Copyright (C) 2022 Graz University of Technology.
# latex_appendices = []
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If false, no module index is generated.
# Copyright (C) 2022 Graz University of Technology.
# latex_domain_indices = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# -- Options for manual page output ---------------------------------------
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# One entry per manual page. List of tuples
# Copyright (C) 2022 Graz University of Technology.
# (source start file, name, description, authors, manual section).
# Copyright (C) 2022 Graz University of Technology.
man_pages = [
# Copyright (C) 2022 Graz University of Technology.
    (master_doc, "flask-breadcrumbs", "Flask-Breadcrumbs Documentation", [author], 1)
# Copyright (C) 2022 Graz University of Technology.
]
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, show URL addresses after external links.
# Copyright (C) 2022 Graz University of Technology.
# man_show_urls = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# -- Options for Texinfo output -------------------------------------------
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Grouping the document tree into Texinfo files. List of tuples
# Copyright (C) 2022 Graz University of Technology.
# (source start file, target name, title, author,
# Copyright (C) 2022 Graz University of Technology.
#  dir menu entry, description, category)
# Copyright (C) 2022 Graz University of Technology.
texinfo_documents = [
# Copyright (C) 2022 Graz University of Technology.
    (
# Copyright (C) 2022 Graz University of Technology.
        master_doc,
# Copyright (C) 2022 Graz University of Technology.
        "Flask-Breadcrumbs",
# Copyright (C) 2022 Graz University of Technology.
        "Flask-Breadcrumbs Documentation",
# Copyright (C) 2022 Graz University of Technology.
        author,
# Copyright (C) 2022 Graz University of Technology.
        "Flask-Breadcrumbs",
# Copyright (C) 2022 Graz University of Technology.
        "One line description of project.",
# Copyright (C) 2022 Graz University of Technology.
        "Miscellaneous",
# Copyright (C) 2022 Graz University of Technology.
    ),
# Copyright (C) 2022 Graz University of Technology.
]
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# Documents to append as an appendix to all manuals.
# Copyright (C) 2022 Graz University of Technology.
# texinfo_appendices = []
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If false, no module index is generated.
# Copyright (C) 2022 Graz University of Technology.
# texinfo_domain_indices = True
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# How to display URL addresses: 'footnote', 'no', or 'inline'.
# Copyright (C) 2022 Graz University of Technology.
# texinfo_show_urls = 'footnote'
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# If true, do not generate a @detailmenu in the "Top" node's menu.
# Copyright (C) 2022 Graz University of Technology.
# texinfo_no_detailmenu = False
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# -- Options for Intersphinx mapping ------------------------------------------
# Copyright (C) 2022 Graz University of Technology.

# Copyright (C) 2022 Graz University of Technology.
# See <http://sphinx-doc.org/ext/intersphinx.html>
# Copyright (C) 2022 Graz University of Technology.
intersphinx_mapping = {
# Copyright (C) 2022 Graz University of Technology.
    "python": ("https://docs.python.org/3/", None),
# Copyright (C) 2022 Graz University of Technology.
    "werkzeug": ("https://werkzeug.palletsprojects.com/en/1.0.x/", None),
# Copyright (C) 2022 Graz University of Technology.
    "flask": ("https://flask.palletsprojects.com/en/1.1.x/", None),
# Copyright (C) 2022 Graz University of Technology.
}
# Copyright (C) 2022 Graz University of Technology.
